### DISCUSSION TITLE
CSS Battle #39 – Sunset

### DISCUSSION THREAD

**Discussion by danieltott** [Virtual-Coffee/virtualcoffee.io#832] [CSS Battles]
### Link to battle:

[Let's battle! ⚔️](https://cssbattle.dev/play/39)

### Copy the code block below to format your comment on the discussion thread:

````md
<details>
<summary>Code Source  – <strong>score {character count}</strong></summary>
<!-- have to be followed by an empty line! -->

```html
your cssbattles code here!
```

</details>
````

### What others will see:

This will result in a nice hidden bit like so:

<details>
<summary>Code Source  – <strong>score {character count}</strong></summary>

```html
your cssbattles code here!
```
</details>

**Comment by danieltott** [comment]
Here's my best attempt (so far! 😁) - **673.33 (178 chars)** using [`radial-gradient`](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/radial-gradient), [`linear-gradient`](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient), and [`clip-path`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path)

<details> 
<summary>Minimized code</summary>


```html
<style>*{background:radial-gradient(circle,#998235 25vw,#1A4341 0)}*>*{margin:80 0;background:linear-gradient(#0000 50%,#F3AC3C 0)0 0/1q 5ch#1A4341;clip-path:circle(125px at 50vw
```
</details>

<details> 
<summary>Readable code</summary>


```css
<style>
* {
  background: radial-gradient(circle, #998235 25vw, #1a4341 0);
}
* > * {
  margin: 80 0;
  background: linear-gradient(#0000 50%, #f3ac3c 0) 0 0/1Q 5ch #1A4341;
  clip-path: circle(125px at 50vw);
}
</style>
```
</details>
