### ISSUE TITLE
"VC GitHub" link on homepage is broken

### ISSUE THREAD

**Issue by malsf21** [Virtual-Coffee/virtualcoffee.io#140]
## Describe the bug

The "VC GitHub" link on the homepage (under "Get Involved") is broken - it leads to a content not found page.

## To Reproduce

1. Go to the [homepage](https://virtualcoffee.io/)
2. Scroll down to "Get Involved"
3. Click "VC GitHub"
4. See: "Content not found"

## Expected behavior

It should take me to the Virtual-Coffee GitHub link!

## Desktop (please complete the following information):

- OS: macOS
- Browser: Chrome (but replicable on each browser)

## Additional context

Not super familiar with the build setup y'all use, but poking around at `src/github.njk`:

```
---
tags:
  - topnav
hero: 'svg/undraw_version_control_9bpv.svg'
homePageBlocks:
  type: small
  key: VC GitHub
  order: 4
eleventyNavigation:
  key: GitHub
  url: https://github.com/Virtual-Coffee
  order: 4
permalink: false
---
```

noticed that the `permalink` key is `false`, and maybe that's being injected as the permalink for that navigation route (instead of `https://github.com/Virtual-Coffee`?). Definitely would defer to someone who is more experienced with eleventy than I am.

More than happy to submit a fix if someone else can verify this!
