### ISSUE TITLE
Add layout for illustration+title/subtitle pattern

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#81]
## Issue Context

We've established a layout pattern that we've used on a lot of pages, where the first block is an illustration + h1 and an optional lead subhead. Some examples:

- https://virtualcoffee.io/members/
- https://virtualcoffee.io/events/
- https://virtualcoffee.io/brownbag-idea/

I think we could create a new layout that uses this, and pass in front matter to set the illustration/h1/subhead

An example of what the front matter could look like for a page:

```yaml
---
layout: "layouts/illustrationHeader.njk"
title: "Brownbag Talk Submission Form"
description: "Submit an idea for a Virtual Coffee Brown Bag talk"
permalink: "brownbag-idea/"
header: "Virtual Coffee: Brownbag"
subhead: "We can't wait to hear your talk!"
illustration: "svg/undraw_Presentation_62e1.svg"
---
```

The `illustrationHeader.njk` layout would extend the `default.njk` layout.

This isn't all set in stone, but I think it could work.

## Alternatives Considered

The other way to do this would be by creating a macro, but the layout pattern would allow a Markdown file to use this nice layout, for example.

## Additional Resources

- [11ty layouts](https://www.11ty.dev/docs/layouts/)
- [11ty layout chaining](https://www.11ty.dev/docs/layout-chaining/)
- [nunjucks macros](https://mozilla.github.io/nunjucks/templating.html#macro)
